### ISSUE TITLE
Accuracy issue

### ISSUE THREAD

**Issue by sreejith-ratnakumar** [dmoulding/log2fix#1]
having low accuracy when input value is less than 0.25. Is this expected

**Comment by dmoulding** [comment]
I'm not able to reproduce any accuracy issue with numbers less than 0.25. Here is a sample run of the tester program that is supplied with the code:

> dan@pal log2fix % ./tester 
> 
> 100
>    log(100.000000) = 4.605170
> logfix(100.000000) = 4.605148
>    log2(100.000000) = 6.643856
> log2fix(100.000000) = 6.643845
>    log10(100.000000) = 2.000000
> log10fix(100.000000) = 1.999985
> 10
>    log(10.000000) = 2.302585
> logfix(10.000000) = 2.302567
>    log2(10.000000) = 3.321928
> log2fix(10.000000) = 3.321915
>    log10(10.000000) = 1.000000
> log10fix(10.000000) = 0.999985
> 1
>    log(1.000000) = 0.000000
> logfix(1.000000) = 0.000000
>    log2(1.000000) = 0.000000
> log2fix(1.000000) = 0.000000
>    log10(1.000000) = 0.000000
> log10fix(1.000000) = 0.000000
> 0.1
>    log(0.100000) = -2.302585
> logfix(0.100000) = -2.302704
>    log2(0.100000) = -3.321928
> log2fix(0.100000) = -3.322083
>    log10(0.100000) = -1.000000
> log10fix(0.100000) = -1.000061
> 0.01
>    log(0.010000) = -4.605170
> logfix(0.010000) = -4.605743
>    log2(0.010000) = -6.643856
> log2fix(0.010000) = -6.644669
>    log10(0.010000) = -2.000000
> log10fix(0.010000) = -2.000259
> 0.001
>    log(0.001000) = -6.907755
> logfix(0.001000) = -6.915985
>    log2(0.001000) = -9.965784
> log2fix(0.001000) = -9.977646
>    log10(0.001000) = -3.000000
> log10fix(0.001000) = -3.003586
> ^C
> 

As you can see it seems to maintain reasonable accuracy even down to 0.1, 0.01, and 0.001. Are you able to reproduce the accuracy issue using the provided tester program? If not, maybe you could share how the code is being used which is exhibiting a problem?

**Comment by sreejith-ratnakumar** [comment]
It was my mistake sorry
